-- ===========================================================================
-- 증분 카테고리(앵커) 엔진 — 임시 후보 / 별칭 / 후보-아이템 연결 / 승격 카테고리 앵커
-- ---------------------------------------------------------------------------
-- AI 서버(ai-test /api/category-engine/decide)는 상태를 저장하지 않고 판단만 한다.
-- 영속 상태(정식 카테고리·후보·연결·별칭·승격 이력)는 백엔드가 소유한다. 아래 4개 테이블이
-- 그 최소 상태다. 첫 잠정 신호와 TTL은 Redis가 보관한다(DB 아님).
-- workspace_id/item_id/category_id 는 기존 패턴대로 FK 없이 생 id 컬럼으로 둔다.
-- ===========================================================================

-- 임시 후보(TemporaryCandidate). 반복되는 핵심 대상을 모아 supportCount 3 이상이면 승격된다.
CREATE TABLE temporary_candidates (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at             timestamp(6) with time zone NOT NULL,
    updated_at             timestamp(6) with time zone NOT NULL,
    workspace_id           bigint                 NOT NULL,
    suggested_name         character varying(100) NOT NULL,
    -- ENTITY | UMBRELLA_TOPIC | OTHER (nullable — 임베딩으로만 형성된 후보는 앵커 없음)
    anchor_type            character varying(20),
    -- 매칭 키(정규화 앵커 이름). ENTITY_EXACT 매칭에 쓴다.
    normalized_anchor_name character varying(100),
    support_count          integer                NOT NULL DEFAULT 0,
    -- PENDING | READY_TO_PROMOTE | PROMOTED | MERGED | EXPIRED | REJECTED
    status                 character varying(20)  NOT NULL DEFAULT 'PENDING',
    -- 승격되면 생성된 정식 카테고리 id
    promoted_category_id   bigint,

    CONSTRAINT pk_temporary_candidates PRIMARY KEY (id)
);
CREATE INDEX ix_temp_candidates_ws_anchor
    ON temporary_candidates (workspace_id, normalized_anchor_name);

-- 후보 별칭(정규화 키). 같은 대상의 다른 표기(짱구/짱구는 못말려/크레용 신짱)를 앵커 매칭에 쓴다.
CREATE TABLE candidate_aliases (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    candidate_id bigint                 NOT NULL,
    alias_key    character varying(100) NOT NULL,

    CONSTRAINT pk_candidate_aliases PRIMARY KEY (id),
    CONSTRAINT uk_candidate_aliases UNIQUE (candidate_id, alias_key)
);

-- 후보 ↔ 아이템 연결. supportCount 산출 근거이며 승격 시 이 아이템들을 새 카테고리로 재분류한다.
CREATE TABLE candidate_item_links (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    candidate_id bigint NOT NULL,
    item_id      bigint NOT NULL,

    CONSTRAINT pk_candidate_item_links PRIMARY KEY (id),
    CONSTRAINT uk_candidate_item_links UNIQUE (candidate_id, item_id)
);

-- 정식 카테고리의 앵커 메타(승격 카테고리 재사용 매칭용). 기존 categories 테이블은 건드리지
-- 않고 별도 테이블로 둔다 — 엔진 메타를 격리한다. SEED 카테고리는 행이 없어도 된다.
CREATE TABLE category_anchors (
    category_id            bigint                NOT NULL,
    -- SEED | AI_PROMOTED
    origin                 character varying(20) NOT NULL,
    anchor_type            character varying(20),
    normalized_anchor_name character varying(100),

    CONSTRAINT pk_category_anchors PRIMARY KEY (category_id)
);
CREATE INDEX ix_category_anchors_norm
    ON category_anchors (normalized_anchor_name);
