-- ===========================================================================
-- workspace_bans
-- ===========================================================================
-- 워크스페이스에서 강제 추방된 유저 기록 — 존재 자체가 재입장 금지를 뜻한다.
-- 자진 탈퇴(LEFT)는 여기 들어가지 않는다.
CREATE TABLE workspace_bans (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    banned_at    timestamp(6) with time zone NOT NULL,
    user_id      bigint                NOT NULL,
    workspace_id bigint                NOT NULL,

    CONSTRAINT pk_workspace_bans PRIMARY KEY (id),
    CONSTRAINT uk_workspace_bans_ws_user UNIQUE (workspace_id, user_id),
    CONSTRAINT fk_workspace_bans_user      FOREIGN KEY (user_id)      REFERENCES users (id),
    CONSTRAINT fk_workspace_bans_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id)
);
